apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=./Dockerfile"
    - "--context=git@github.com:ryanzhang/tekton-pipeline-example-app.git#master"
    - "--destination=quay.io/rzhang"
    # volumeMounts:
    # - name: kaniko-secret
    #   mountPath: /secret
    # env:
    # - name: GOOGLE_APPLICATION_CREDENTIALS
    #   value: /secret/kaniko-secret.json
  restartPolicy: Never
  # volumes:
  # - name: kaniko-secret
  #   secret:
  #     secretName: kaniko-secret
